"""Export the MIS6 event ages retained as Supporting Information Table S1.

Run from the project root or manuscript directory. All other numerical results
remain in their original analysis outputs; no models are fitted here.
"""
from pathlib import Path
import hashlib

import pandas as pd

PROJECT = Path(__file__).resolve().parent
SOURCE = Path('data/curated/ngrip_mis6_warming_events.csv')
OUT = PROJECT / 'orbital_event_paper/tables'


def main():
    # Retain the timing assignments made in this study, with published labels.
    events = pd.read_csv(PROJECT / SOURCE)
    columns = ['event_label', 'source_record', 'source_event_label', 'event_age_kyr_bp']
    mis6 = events.loc[events.segment_id.eq('MIS6'), columns].copy()
    OUT.mkdir(parents=True, exist_ok=True)
    mis6.to_csv(OUT / 'S1_MIS6_event_ages.csv', index=False)

    # Millennial ages are displayed to one year; this is numerical resolution,
    # not dating precision. Keep the full stored values in the companion CSV.
    displayed = mis6.rename(columns={
        'event_label': 'Composite event',
        'source_record': 'Record',
        'source_event_label': 'Published label',
        'event_age_kyr_bp': 'Age (kyr BP)',
    })
    latex = displayed.to_latex(index=False, escape=True, column_format='lllr',
                              float_format=lambda age: f'{age:.3f}')
    (OUT / 'TableS1.tex').write_text(
        '% Generated by paper_tables.py; edit the exporter, not this file.\n'
        + '{\\small\n\\centering\n' + latex + '\\par}\n', encoding='utf-8')
    pd.DataFrame([{
        'source_file': str(SOURCE),
        'sha256': hashlib.sha256((PROJECT / SOURCE).read_bytes()).hexdigest(),
    }]).to_csv(OUT / 'source_manifest.csv', index=False)
    print(f'Exported {len(mis6)} MIS6 event ages to {OUT}.')


if __name__ == '__main__':
    main()
